Refactor API Endpoints
AstarNetwork/astar-token-api pull request #72
Opened 2023-05-31 14:16 UTC by MarcoB95-lab

1 - The "HTTP" schema has been removed because the endpoint api.astar.network automatically redirects from port 80 to 443, making the HTTP schema unnecessary.
Previously, "HTTP" was the default schema, which consistently resulted in errors when querying the API endpoints.
Error: Undocumented - TypeError: NetworkError when attempting to fetch resource.

2 - Refactor API Endpoints to Replace Textfields with Enum Parameters
This pull request introduces a significant enhancement to our API endpoints by replacing all textfield inputs with enum parameters. This change is aimed at improving the user experience and reducing potential errors.

Previously, our API endpoints accepted general string inputs, which could lead to potential errors or confusion if an unsupported or incorrect value was entered. With this update, we are replacing these open textfields with dropdown selections, where users can only choose from a predefined set of options.

This change enforces stricter input validation across all endpoints, thereby improving the robustness and reliability of our API. It also simplifies the user interaction, as users can now select from available options rather than manually inputting values.

The changes have been implemented across all API endpoints. Each endpoint's Swagger definition has been updated to reflect these changes, with the 'type' of relevant parameters changed from 'string' to 'enum', and the acceptable values defined accordingly.

Missing network information, which endpoints are allowed, for the following urls:
/api/v1/{network}/dapps-staking/stats/transactions
/api/v1/{network}/dapps-staking/stats/uaw
/api/v1/{network}/dapps-staking/stats/nexteraeta

@bobo-k2

2023-06-05 09:05 UTC, impelcrypto approved these changes

2023-06-05 16:26 UTC, MarcoB95-lab commented
@bobo-k2 and @impelcrypto Thank you for the review!
Can you comment again on the Tier and Rating in % following this description: https://github.com/AstarNetwork/growth-program/blob/main/ui-dao.md

So I can receive a reward from @togamamora

2023-06-06 07:54 UTC, bobo-k2 requested changes

2023-06-06 07:54 UTC, bobo-k2 commented on src/swagger.js
> +    schemes: ['https'],
I have concern here, how I can test this locally without SSL. Maybe just to change schemes order so `https` comes first. I assume it will be selected as default on swagger ui.

2023-06-06 07:54 UTC, bobo-k2 commented
> @bobo-k2 and @impelcrypto Thank you for the review! Can you comment again on the Tier and Rating in % following this description: https://github.com/AstarNetwork/growth-program/blob/main/ui-dao.md
> 
> So I can receive a reward from @togamamora

Sure, I will do that as soon as we merge the PR, but please address the comment first.

2023-06-06 11:28 UTC, MarcoB95-lab commented
Thats the error you get when using the http endpoint over the website https://api.astar.network. So if there is no http endpoint, why display it on the website?
![grafik](https://github.com/AstarNetwork/astar-token-api/assets/84941542/d0d7adef-cc16-4565-ba9a-3518e1ff3eeb)

But I understand what you mean and changed it.
@bobo-k2 - Please review it.

2023-06-15 12:38 UTC, MarcoB95-lab commented
Hey @bobo-k2 I updated the code. Am I still missing something?

2023-06-16 08:38 UTC, bobo-k2 commented
> Hey @bobo-k2 I updated the code. Am I still missing something?

I apologize for being slow.
@togamamora this id done 100%

2023-06-16 17:29 UTC, MarcoB95-lab commented
No worries! Really appreciate you commenting and reviewing all of it @bobo-k2 :). Thank you very much. 

Which tier would you list the PR in?

2023-06-22 23:31 UTC, togamamora commented
@bobo-k2 

Just to double confirm:

1. Which Tier is this?
2. What is the rating 1 to 5? 1 being the lowest.

2023-06-27 14:19 UTC, bobo-k2 commented
> @bobo-k2
> 
> Just to double confirm:
> 
> 1. Which Tier is this?
> 2. What is the rating 1 to 5? 1 being the lowest.

@togamamora Confirming Tier 1, rating 5

2023-06-28 01:45 UTC, togamamora commented
Thanks @bobo-k2 

@MarcoB95-lab Please add this in your monthly contribution report.

2023-07-03 07:23 UTC, bobo-k2 approved these changes

2023-07-03 07:23 UTC, merged